services:
  bot:
    build:
      context: .
      target: develop
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
  database:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - '8000:8080'
volumes:
  pgdata:
    driver: local
