services:
  bot:
    build: .
    image: ${CI_IMAGE}
    restart: always
    ports:
      - '8080:8080'
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: 'postgresql://test@database/db?schema=public'
  database:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
