services:
  app:
    image: telegram-bot
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/mydatabase
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: