name: Deploy
on:
  push:
    branches:
      - master
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: node_modules-
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
      - run: npm run deploy
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          IMAGE: ${{ secrets.DOCKER_HUB_IMAGE }}
